[package]
name = "kings-walk"
version = "0.1.0"
authors = ["tim nosco <tim.nosco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
